// GENERATED BY FLUTTERFIRE CLI. DO NOT EDIT.
// File generated from google-services.json via manual transcription to unblock
// Firebase initialization in this repository. If configuration changes, run
// `flutterfire configure` to regenerate this file.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] used across platforms.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'FirebaseOptions have not been configured for web. Run flutterfire configure to regenerate firebase_options.dart with web support.',
      );
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'FirebaseOptions are not configured for ${defaultTargetPlatform.name}. Run flutterfire configure to regenerate firebase_options.dart.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA07inF1W8iLZSr7geIPfKNvNT_rjNqSRQ',
    appId: '1:335231985992:android:0dc7586353da4e00cbab7d',
    messagingSenderId: '335231985992',
    projectId: 'edums-app',
    storageBucket: 'edums-app.firebasestorage.app',
  );
}
